"""add catalog import tables

Revision ID: e0afbcaa4e94
Revises: aeb335964505
Create Date: 2026-08-27 11:32:54.182052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0afbcaa4e94'
down_revision: Union[str, Sequence[str], None] = 'aeb335964505'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('supplier_name', sa.String(length=150), nullable=True),
    sa.Column('effective_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('imported_rows', sa.Integer(), nullable=False),
    sa.Column('failed_rows', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_imports_id'), 'catalog_imports', ['id'], unique=False)
    op.create_table('catalog_import_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_id', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('row_number', sa.Integer(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('parsed_status', sa.String(length=30), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['catalog_imports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_import_rows_import_id'), 'catalog_import_rows', ['import_id'], unique=False)
    op.create_table('catalog_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('import_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('standard_package', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['catalog_imports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_prices_import_id'), 'catalog_prices', ['import_id'], unique=False)
    op.create_index(op.f('ix_catalog_prices_product_id'), 'catalog_prices', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_catalog_prices_product_id'), table_name='catalog_prices')
    op.drop_index(op.f('ix_catalog_prices_import_id'), table_name='catalog_prices')
    op.drop_table('catalog_prices')
    op.drop_index(op.f('ix_catalog_import_rows_import_id'), table_name='catalog_import_rows')
    op.drop_table('catalog_import_rows')
    op.drop_index(op.f('ix_catalog_imports_id'), table_name='catalog_imports')
    op.drop_table('catalog_imports')
    # ### end Alembic commands ###
